# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Capstone' do
  pod 'CocoaMQTT'

  # Pods for Capstone

  target 'CapstoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CapstoneUITests' do
    # Pods for testing
  end

end
